# This rule is not used by the project workloadautoscale-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to autoscale.cicd.operator resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workloadautoscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadautoscale-viewer-role
rules:
- apiGroups:
  - autoscale.cicd.operator
  resources:
  - workloadautoscales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscale.cicd.operator
  resources:
  - workloadautoscales/status
  verbs:
  - get
