apiVersion: autoscale.cicd.operator/v1
kind: WorkloadAutoscale
metadata:
  labels:
    app.kubernetes.io/name: workloadautoscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: executor-autoscale
spec:
  inputQueue:
    host: "job-queue"
    port: 5673
    username: "guest"
    passwordSecretRef:
      name: "rabbitmq-credentials"
      key: "password"
    queueName: "job_queue"

  database:
    host: "mysql-3a59b330-auction-mysql.f.aivencloud.com"
    port: 15718
    username: "avnadmin"
    passwordSecretRef:
      name: "mysql-secret"
      key: "DB_PASSWORD"
    name: "CicdApplication"
    sslMode: "true"
    sslCASecretRef:
      name: "db-ca-cert"
      key: "ca.pem"

  storage:
    host: "minio"
    accessKeyRef:
      name: "minio-keys"
      key: "CONSOLE_ACCESS_KEY"
    secretKeyRef:
      name: "minio-keys"
      key: "CONSOLE_SECRET_KEY"
    defaultBucket: "default"

  cache:
    host: "redis-14178.c258.us-east-1-4.ec2.redns.redis-cloud.com"
    port: 14178
    username: "default"
    passwordSecretRef:
      name: "redis-secret"
      key: "REDIS_PASSWORD"

  workerPool:
    workerImage: "minh160302/job-executor"
    workerImageTag: "latest"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

  scaling:
    pollingIntervalSeconds: 5

